### ISSUE TITLE
Full History Dialog displaying behind toolbar in version 8.1

### ISSUE THREAD

**Issue by wclifton87** [onenorth/workflow-full-history#1]
I just installed the latest release and I am getting some strange UI behavior when I click the "Full History" button (please see screenshot, attached).  I have tried it in Chrome and IE and I get the same thing.  

Thanks!
![full_history_issue1](https://cloud.githubusercontent.com/assets/19536313/15481290/bee984aa-20f7-11e6-940d-688fa44a11cd.jpg)

**Comment by peteamundson** [comment]
This hasn't been tested in Sitecore 8.x.  I'll review the styling and update for the changes in the interface.

**Comment by wclifton87** [comment]
Cool.  Thanks.  For what it's worth, I was able to fix the issue locally by bumping up the z-index on the scPopup class that Sitecore uses.  (Not a great solution, obviously.)  I also had to hardcode the width of the main div in the WorkflowFullHistoryPopup.cshtml.

**Comment by peteamundson** [comment]
The update to SPEAK UI broke this.  I have updated the code in the sitecore-8.1 branch to fix this and follow a more consistent design.  We'll get a release put together but in the mean time you can recompile and drop the dll in your bin manually.

**Comment by mskutta** [comment]
I created a Sitecore 8.1 release based on Pete's changes.  The release is labeled **v1.1.0 (Sitecore 8.1)**.  Let us know if you run into any issues.

**Comment by wclifton87** [comment]
I just installed the new release.  It works!  Thanks.
